"""dynaris: A JAX-powered Python library for Dynamic Linear Models (DLMs)."""

from dynaris.core import (
    SSM,
    FilterProtocol,
    FilterResult,
    GaussianState,
    MarkovSwitchingSSM,
    NonlinearSSM,
    SmootherProtocol,
    SmootherResult,
    StateSpaceModel,
    SwitchingFilterResult,
    SwitchingSmootherResult,
)
from dynaris.dlm import (
    DLM,
    Autoregressive,
    Cycle,
    LocalLevel,
    LocalLinearTrend,
    Regression,
    Seasonal,
)
from dynaris.filters import (
    ExtendedKalmanFilter,
    HamiltonFilter,
    KalmanFilter,
    ParticleFilter,
    UnscentedKalmanFilter,
    ekf_filter,
    hamilton_filter,
    kalman_filter,
    particle_filter,
    ukf_filter,
)
from dynaris.models import (
    BearingsTracking,
    LorenzAttractor,
    StochasticVolatility,
    transform_returns,
)
from dynaris.smoothers import KimSmoother, RTSSmoother, kim_smooth, rts_smooth

__version__ = "0.1.0"

__all__ = [
    "DLM",
    "SSM",
    "Autoregressive",
    "BearingsTracking",
    "Cycle",
    "ExtendedKalmanFilter",
    "FilterProtocol",
    "FilterResult",
    "GaussianState",
    "HamiltonFilter",
    "KalmanFilter",
    "KimSmoother",
    "LocalLevel",
    "LocalLinearTrend",
    "LorenzAttractor",
    "MarkovSwitchingSSM",
    "NonlinearSSM",
    "ParticleFilter",
    "RTSSmoother",
    "Regression",
    "Seasonal",
    "SmootherProtocol",
    "SmootherResult",
    "StateSpaceModel",
    "StochasticVolatility",
    "SwitchingFilterResult",
    "SwitchingSmootherResult",
    "UnscentedKalmanFilter",
    "__version__",
    "ekf_filter",
    "hamilton_filter",
    "kalman_filter",
    "kim_smooth",
    "particle_filter",
    "rts_smooth",
    "transform_returns",
    "ukf_filter",
]
